[package]
name = "todo-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
todo-domain = { path = "../todo-domain" }
ciborium = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
snow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
x25519-dalek = { workspace = true }
